import {useState,type FormEvent} from 'react';
import {ArrowRight,Check,Eye,EyeOff,Leaf,ShieldCheck} from 'lucide-react';
import {Button,Field,Notice} from '../ui';
import {request} from '../api';

export function Auth({onLogin}:{onLogin:()=>void}){
 const [mode,setMode]=useState<'login'|'forgot'>('login');const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[show,setShow]=useState(false);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');setMessage('');try{const data=Object.fromEntries(new FormData(e.currentTarget));if(mode==='forgot'){const result=await request<any>('/api/auth/forgot-password',{email:data.login});setMessage(result.message)}else{await request('/api/auth/login',{companyCode:data.companyCode,login:data.login,password:data.password});onLogin()}}catch(err){setError((err as Error).message)}finally{setBusy(false)}};
 return <main className="auth-layout"><section className="auth-story"><a className="brand" href="/"><span className="brand-symbol"><Leaf size={23}/></span>TrueCare<span className="brand-dot">.</span></a><div className="auth-story-content"><div className="eyebrow">KHÔNG GIAN LÀM VIỆC CỦA BẠN</div><h1>Bán hàng rõ ràng.<br/>Quỹ dư trong tầm tay.</h1><p>Từ một toa hàng đến cả ngày đi tuyến, theo dõi mọi con số ở cùng một nơi.</p><div className="auth-preview"><div className="preview-label"><span className="green-dot"/> Mỗi giao dịch, một nguồn đối chiếu</div>{['Doanh số đặt và thực giao tách biệt','Quỹ chỉ ghi nhận từ hàng đã giao','Dữ liệu riêng cho từng nhân viên'].map(text=><div className="preview-row" key={text}><Check size={17}/>{text}</div>)}</div></div><div className="auth-foot">TRUECARE · SALES WORKSPACE <span>Thiết kế cho ngày bán hàng của bạn</span></div></section><section className="auth-form-side"><div className="auth-form"><div className="mobile-brand"><Leaf/> TrueCare</div><div className="eyebrow green-text">TRUECARE NHÂN VIÊN</div><h2>{mode==='login'?'Chào mừng bạn trở lại':'Khôi phục mật khẩu'}</h2><p>{mode==='login'?'Đăng nhập bằng email hoặc tên đăng nhập do quản trị viên cấp.':'Nhập email hoặc tên đăng nhập đã được cấp.'}</p>{error&&<Notice type="error">{error}</Notice>}{message&&<Notice type="success">{message}</Notice>}<form key={mode} onSubmit={submit} className="form-stack">{mode==='login'&&<Field label="Mã công ty"><input name="companyCode" defaultValue="TRUECARE" required/></Field>}<Field label="Email hoặc tên đăng nhập"><input name="login" required autoComplete={mode==='login'?'username':'email'}/></Field>{mode==='login'&&<Field label="Mật khẩu"><div className="password-input"><input name="password" type={show?'text':'password'} required autoComplete="current-password"/><button type="button" aria-label={show?'Ẩn mật khẩu':'Hiện mật khẩu'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></Field>}{mode==='login'&&<button className="text-button align-right" type="button" onClick={()=>{setMode('forgot');setError('');setMessage('')}}>Quên mật khẩu?</button>}<Button variant="primary" className="full" busy={busy}>{mode==='login'?'Đăng nhập':'Gửi hướng dẫn'}<ArrowRight size={17}/></Button></form><div className="auth-switch">{mode==='login'?'Cần tài khoản mới?':'Đã nhớ mật khẩu?'} <button className="text-button" onClick={()=>{setMode(mode==='login'?'forgot':'login');setError('');setMessage('')}}>{mode==='login'?'Liên hệ quản trị viên':'Đăng nhập'}</button></div><div className="auth-security"><ShieldCheck size={16}/> Tài khoản do quản trị viên TrueCare cấp</div></div></section></main>;
}
