import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useWorkspace } from "../api";
import { Button, Card, Empty, Field, Heading, Modal, Notice, Status, day, money, today } from "../ui";
import type { OrderLine, Program } from "../../shared/types";

type SmartOption = { id: string; label: string; token: string; price: string; margin: string; subsidy: string; totalReserved: string; availableAfter: string; cases: number; skuCount: number; variantCount: number; gift?: { id: string; name: string; value: string }; lines: OrderLine[]; };
type SmartPreview = { options: SmartOption[]; reasons: string[]; excluded: { id: string; name: string; reason: string }[]; pricebook: { sourceName: string; effectiveDate: string } };

export function Programs() {
  const { state, command, workspaceRequest, busy, user, adminTarget } = useWorkspace();
  const navigate = useNavigate();
  const [filter, setFilter] = useState("active"), [count, setCount] = useState(1), [expires, setExpires] = useState(today());
  const [preview, setPreview] = useState<SmartPreview | null>(null), [error, setError] = useState("");
  const [applying, setApplying] = useState<Program | null>(null), [customerId, setCustomerId] = useState(""), [useCount, setUseCount] = useState(1);
  const [archiving, setArchiving] = useState<Program | null>(null);
  const canManage = user.role === "admin";
  const status = (p: Program) => p.archivedAt ? "archived" : p.status === "active" && p.expiresAt < today() ? "expired" : p.status;
  const rows = state.programs.filter((p) => filter === "all" || status(p) === filter);
  const customers = state.customers.filter((c) => !c.archived && !c.deletedAt && !c.mergedInto);
  const generate = async () => { setError(""); setPreview(null); try { setPreview(await workspaceRequest<SmartPreview>("/api/programs/smart-preview", { count, expiresAt: expires })); } catch (cause) { setError((cause as Error).message); } };
  const save = async (option: SmartOption) => { setError(""); try { await command("reserveSmartProgram", { token: option.token, reason: "Lưu chương trình thông minh" }); setPreview(null); } catch (cause) { setError((cause as Error).message); } };
  const apply = async () => { if (!applying) return; setError(""); try { const result = await command("applyProgram", { id: applying.id, customerId, count: useCount, date: today() }); const order = result.orders.find((item) => item.id === result.commandResult?.orderId); setApplying(null); if (order) navigate(`/orders/${order.id}`); } catch (cause) { setError((cause as Error).message); } };
  const archive = async () => { if (!archiving) return; setError(""); try { await command("archiveProgram", { id: archiving.id, reason: "Lưu trữ chương trình theo yêu cầu quản trị" }); setArchiving(null); } catch (cause) { setError((cause as Error).message); } };
  return <>
    <Heading title="Chương trình chào hàng" description="Tạo phương án tự động theo giá trần đã chốt; xem trước không giữ quỹ hay tồn." />
    {error && !applying && <Notice type="error">{error}</Notice>}
    <div className="program-grid smart-program-grid">
      <Card title="Tạo chương trình thông minh" subtitle="Tự chọn toàn bộ hàng đủ điều kiện, ưu tiên dùng quỹ thấp nhất.">
        {canManage ? <div className="form-stack"><div className="form-grid"><Field label="Số suất"><input aria-label="Số suất" type="number" min="1" max="1000000" value={count} onChange={(event) => setCount(Number(event.target.value))} /></Field><Field label="Hết hạn"><input aria-label="Hết hạn" type="date" min={today()} value={expires} onChange={(event) => setExpires(event.target.value)} /></Field></div><Notice>Mỗi suất bù tối đa 200.000đ. Giá bán không vượt giá thấp hơn giữa catalog và bảng giá chương trình. Chỉ phương án được chọn mới giữ quỹ/tồn.</Notice><Button variant="primary" busy={busy} disabled={!Number.isSafeInteger(count) || count < 1 || expires < today()} onClick={() => void generate()}>Tạo phương án</Button>{preview && <SmartOptions preview={preview} products={state.products} onSave={save} busy={busy} />}</div> : <Notice type="warning">Chỉ quản trị viên được tạo hoặc lưu chương trình thông minh. Bạn vẫn có thể dùng các suất đang hoạt động.</Notice>}
      </Card>
      <Card title="Chương trình đã lưu"><Field label="Trạng thái chương trình"><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="active">Đang hoạt động</option><option value="expired">Hết hạn</option><option value="cancelled">Đã hủy</option><option value="archived">Đã lưu trữ</option><option value="all">Tất cả</option></select></Field>{rows.length ? <div className="program-list">{rows.map((program) => <div key={program.id} className="smart-program-row"><div><strong>{program.name}</strong><small>{program.remaining}/{program.count} suất · hết hạn {day(program.expiresAt)}</small>{program.smart && <small>{program.smart.giftId ? `Tặng phẩm đã chốt: ${program.lines.find((line) => line.virtualGift)?.name ?? program.smart.giftId}` : "Không tặng phẩm"} · {program.smart.cases} thùng/suất</small>}</div><span><Status value={status(program)} /><b>Giữ {money(status(program) === "active" ? program.reserved : "0")}</b></span><div className="program-actions"><Button disabled={status(program) !== "active" || program.remaining < 1} onClick={() => { setApplying(program); setUseCount(1); setCustomerId(""); setError(""); }}>Dùng suất</Button>{canManage && !program.archivedAt && <Button variant="danger" disabled={busy} onClick={() => setArchiving(program)}>Xóa chương trình</Button>}</div></div>)}</div> : <Empty title="Chưa có chương trình phù hợp" description="Đổi bộ lọc hoặc tạo phương án mới." />}</Card>
    </div>
    {applying && <Modal title="Dùng suất tạo toa" onClose={() => !busy && setApplying(null)}><div className="form-stack">{error && <Notice type="error">{error}</Notice>}<Notice>{applying.name}. Hệ thống tạo toa đã chốt và chuyển quỹ giữ sang toa. {adminTarget && `Đang thao tác cho ${adminTarget.displayName}.`}</Notice><Field label="Khách hàng nhận suất"><select value={customerId} onChange={(event) => setCustomerId(event.target.value)}><option value="">Chọn khách</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></Field><Field label="Số suất sử dụng"><input type="number" min="1" max={applying.remaining} value={useCount} onChange={(event) => setUseCount(Number(event.target.value))} /></Field><p>Tổng giá trị: {money(Number(applying.price) * (Number.isFinite(useCount) ? useCount : 0))} · còn lại: {applying.remaining - useCount} suất.</p><div className="modal-actions"><Button disabled={busy} onClick={() => setApplying(null)}>Hủy</Button><Button variant="primary" busy={busy} disabled={!customerId || !Number.isSafeInteger(useCount) || useCount < 1 || useCount > applying.remaining} onClick={() => void apply()}>Xác nhận tạo toa</Button></div></div></Modal>}
    {archiving && <Modal title="Xóa chương trình đã lưu" onClose={() => !busy && setArchiving(null)}><div className="form-stack"><Notice type="warning">Chương trình “{archiving.name}” sẽ được lưu trữ. Các suất còn lại bị hủy và giải phóng {money(archiving.reserved)}; toa đã tạo và lịch sử không thay đổi.</Notice><div className="modal-actions"><Button disabled={busy} onClick={() => setArchiving(null)}>Hủy</Button><Button variant="danger" busy={busy} onClick={() => void archive()}>Lưu trữ chương trình</Button></div></div></Modal>}
  </>;
}

function SmartOptions({ preview, products, onSave, busy }: { preview: SmartPreview; products: { id: string; name: string; variant: string }[]; onSave: (option: SmartOption) => void; busy: boolean }) {
  return <div className="smart-options" aria-live="polite"><strong>Phương án hợp lệ</strong><small>Nguồn giá: {preview.pricebook.sourceName} · hiệu lực từ {day(preview.pricebook.effectiveDate)}.</small>{preview.options.map((option) => <article key={option.token} className="smart-option"><header><div><strong>{option.label}</strong><small>{option.cases} thùng · {option.skuCount} SKU · {option.variantCount} màu/biến thể</small></div><b>Bù {money(option.subsidy)}/suất</b></header><div className="smart-option-lines">{option.lines.map((line) => <span key={line.id}>{line.kind === "gift" ? "Tặng " : ""}{line.name}{line.kind === "sale" ? ` · ${line.quantity} ${line.unit} · ${money(line.price)}` : ` · ${money(line.cost)}`}{line.kind === "sale" && products.find((product) => product.id === line.productId)?.variant ? ` · ${products.find((product) => product.id === line.productId)?.variant}` : ""}</span>)}</div><p>Giá chào: <b>{money(option.price)}</b> · Quỹ giữ: <b>{money(option.totalReserved)}</b> · Quỹ còn: <b>{money(option.availableAfter)}</b></p><Button variant="primary" busy={busy} onClick={() => onSave(option)}>Chọn & lưu chương trình</Button></article>)}{!preview.options.length && <Empty title="Chưa có phương án hợp lệ" description="Kiểm tra quỹ, bảng giá, giá vốn và tồn kho." />}{preview.reasons.map((reason) => <Notice key={reason} type="warning">{reason}</Notice>)}{preview.excluded.length > 0 && <Notice>{preview.excluded.length} sản phẩm không được dùng vì thiếu ánh xạ bảng giá. Cập nhật bảng giá phiên bản mới để thêm chúng.</Notice>}</div>;
}
