export type Money = string;
export interface User { id:string; email:string; username:string; displayName:string }
export interface Product {id:string; name:string; code:string; group:string; brand:string; variant:string; unit:string; pack:number; cost:Money|null; price:Money|null; effectiveDate:string; archived?:boolean}
export interface Customer {id:string; name:string; contact:string; phone:string; email:string; address:string; street:string; ward:string; district:string; province:string; route:string; visitDays:number[]; frequency:string; storeType:string; notes:string; openedDate:string; archived?:boolean}
export interface OrderLine {id:string; productId:string; name:string; quantity:number; price:Money; cost:Money|null; ceiling:Money|null; pack:number; unit:string; kind:'sale'|'gift'|'display'; sponsor:'employee'|'company'; discount:Money; delivered:number; returned:number; fixedPrice?:boolean}
export interface Order {id:string; code:string; customerId:string; date:string; notes:string; status:'draft'|'confirmed'|'partial'|'delivered'|'cancelled'; lines:OrderLine[]; total:Money; margin:Money|null; reserved:Money; version:number; historical?:boolean; programId?:string; bundleCount?:number; cancelReason?:string}
export interface Delivery {id:string; code:string; orderId:string; date:string; lines:{lineId:string; quantity:number; revenue:Money; margin:Money|null}[]; total:Money; margin:Money|null; notes:string}
export interface ReturnRecord {id:string; deliveryId:string; orderId:string; date:string; lines:{lineId:string; quantity:number; restock:boolean; revenue:Money; margin:Money|null}[]; reason:string}
export interface LedgerEntry {id:string; date:string; type:'opening'|'delivery'|'return'|'adjustment'; amount:Money; referenceId:string; notes:string}
export interface Inventory {productId:string; quantity:number; tracked:boolean; updatedAt:string; source:string}
export interface InventoryMovement {id:string; productId:string; date:string; quantity:number; reason:string; referenceId:string}
export interface Program {id:string; name:string; mode:'bundle'|'single'; lines:OrderLine[]; count:number; remaining:number; price:Money; margin:Money; subsidy:Money; reserved:Money; guaranteeStock:boolean; status:'active'|'cancelled'|'expired'; expiresAt:string; seed:number}
export interface Settings {displayName:string; companyCode:string; dailyTarget:Money; monthlyTarget:Money; newCustomerTarget:number; aso:number; theme:'light'|'dark'; workDays:number[]; holidays:string[]; focusProduct:string; periodStart:string; openingSales:Money; reportGroups:string[]; [key:string]:unknown}
export interface AppState {version:number; products:Product[]; customers:Customer[]; orders:Order[]; deliveries:Delivery[]; returns:ReturnRecord[]; payments:{id:string;orderId:string;date:string;amount:Money;notes:string}[]; ledger:LedgerEntry[]; programs:Program[]; inventory:Inventory[]; inventoryMovements:InventoryMovement[]; visits:{id:string;customerId:string;date:string;notes:string}[]; settings:Settings; audit:{id:string;at:string;type:string;referenceId:string;details:string}[]; imports:{hash:string;at:string}[]; summary:{ordered:Money;delivered:Money;collected:Money;fund:Money;reserved:Money;available:Money;pendingMargin:Money;unresolved:number}}
export interface Command {type:string; payload:any; idempotencyKey:string; version?:number}
